version: '3.8'

services:
  ki-analyse:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    ports:
      - "8095:80"
    restart: unless-stopped
